version: '3.8'
services:
  web:
    build:
      context: ./
    volumes:
      - .:/src
    command: npm run start
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      DEBUG: nodejs-docker-express:*